services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bar_management
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
  staff-api:
    build:
      context: ./staff-api
      args:
        JAR: ./target/*.jar
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bar_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  customer-api:
    build:
      context: ./customer-api
      args:
        JAR: ./target/*.jar
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bar_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres